# Generated by Django 3.0.6 on 2020-10-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0046_user_is_influencer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_influencer',
            field=models.BooleanField(default=False),
        ),
    ]
